### ISSUE TITLE
Notifications look slightly strange on OS X 10.10.3

### ISSUE THREAD

**Issue by carbureted** [cgrossde/nw-notify#1]
![screen shot 2015-02-26 at 5 16 16 pm](https://cloud.githubusercontent.com/assets/597441/6405670/3783f82c-bddb-11e4-971a-48ae08acbe8b.png)

**Comment by cgrossde** [comment]
Thanks for the notice, I don't have 10.10.3 (yet) but I will address this issue once it gets released. Can you tell me if you use a Mac with Retina screen?

**Comment by cgrossde** [comment]
I just released a new version of nw-notify. It works for me on Mac 10.10.3, please test if you can still reproduce this error and feel free to reopen this issue.
