### ISSUE TITLE
Not working as it should

### ISSUE THREAD

**Issue by makkesk8** [cgrossde/nw-notify#10]
Uncaught TypeError: Cannot read property 'style' of null index.js:479

Not working at all.

Running latest version of nw.js

**Comment by cgrossde** [comment]
Which OS? How do you use it (source)?

**Comment by makkesk8** [comment]
Windows 10, Using the example provided.

**Comment by cgrossde** [comment]
I just spent two hours getting Win 10 and setting it up in a vm. I could not reproduce your issue. It works with the example in the test folder and also the nw-sample-apps notification demo.
![test_win10_32](https://cloud.githubusercontent.com/assets/2333584/9518183/0b7bf11c-4cb5-11e5-977d-5500c7388dfc.png)

I used Node 0.12.7 as well es NW.JS 0.12.3 on a Win 10 x32. Please provide more info about your configuration.

**Comment by makkesk8** [comment]
Oh i see, well I will try again :)

**Comment by makkesk8** [comment]
<script>
    var nwNotify = require('nw-notify');
    nwNotify.notify('Some title', 'Some text');
  </script>

Top of index.html

Still getting: Uncaught TypeError: Cannot read property 'style' of null - index.js:479

I'm also using angular & jquery if that makes any difference
