### ISSUE TITLE
Close Button Shows Edit Cursor Icon on Mouse over

### ISSUE THREAD

**Issue by ghostfreak3000** [cgrossde/nw-notify#13]
Could the close buttong on a notification show the default cursor icon?

**Comment by ghostfreak3000** [comment]
Decided to fork the project

**Comment by cgrossde** [comment]
You can change this already: 

```Javascript 
nwNotify.setConfig({
  defaultStyleClose: {
    cursor: "pointer"
  }
});
```

Take a look at [index.js:L76](https://github.com/ghostfreak3000/nw-notify/blob/0daaa50b69a998a3ae02cae6f9c1e096e9198424/index.js#L76) for styling options.
