### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by makkesk8** [cgrossde/nw-notify#15]
I really like this project and I'm using it in all my nw.js apps. But it lacks so many awesome features that chrome has... for instance: https://developer.chrome.com/apps/richNotifications

I would really like to see something like this being implemented. I would love to do it my self but I do lack the time for it atm. However, I will definitely create a pr if I can get to it :)

Thoughts?

**Comment by cgrossde** [comment]
Same problem here: lack of time ^^. Also I would really like to keep this thing as simple as possible. Don't know if rich notifications will bloat it. But wouldn't turn down a good PR ;)

**Comment by makkesk8** [comment]
Made a new [PR](https://github.com/cgrossde/nw-notify/pull/19) for some stuff i already implemented in my local version, will probably implement more features as i need them and make pr's
