### ISSUE TITLE
Cannot reinitialize notifications after closeAll() is called

### ISSUE THREAD

**Issue by drown-zed** [cgrossde/nw-notify#16]
After closeAll() is called, it's no longer possible to send new notifications.
Sometimes I need to to do location.reload(), so I'm required to call closeAll() function before that. After the page reloads notifications can no longer be sent. Only after restarting the node webkit application notifications start working again.

**Comment by cgrossde** [comment]
Try clearing the window arrays after closing them [index.js#505](https://github.com/cgrossde/nw-notify/blob/master/index.js#L505)
```
activeNotifications = [];
inactiveWindows = [];
```

If that resolves your problem a pull-request would be very much appreciated.

**Comment by drown-zed** [comment]
Sorry, doesn't seem to resolve the issue with location.reload(). However it does work when i manually reload with dev toolbar

**Comment by cgrossde** [comment]
Can you share your project/code?

**Comment by drown-zed** [comment]
I can share the test code where you could reproduce the issue:
https://github.com/drown-zed/NotificationTest

**Comment by cgrossde** [comment]
Thanks for providing the test code. I could locate the bug and fixed it.

**Comment by drown-zed** [comment]
Great work. Thanks!
