### ISSUE TITLE
Link back to main application

### ISSUE THREAD

**Issue by alexcroox** [cgrossde/nw-notify#2]
First off, thank you so much for this great module!

I want to be able to link back to the main application rather than just an external web link. 

For example if the main app window is hidden behind others, or minimised, if I could make the default behaviour for clicking on the notification; maximise the window and bring it to the front (Windows)

**Comment by cgrossde** [comment]
Hey,

you can do this by providing a callback function for the click event.

**notify(title, text, url, image, onClickFunction)**

Example:
```
// Do something when user clicks on notification
nwNotify.notify('Custom func','Action on click', null, null, function() {
    // Your code here will be executed on click
});
```

**Comment by alexcroox** [comment]
Ah perfect thank you!
