### ISSUE TITLE
Problem when initializing nw-notify

### ISSUE THREAD

**Issue by drown-zed** [cgrossde/nw-notify#27]
Using the latest version of nw (0.17.6) it's not possible to initialize nw-notify.
require('nw-notify') throws an error:
`cannot get current window; are you in background page/node context?`

**Comment by cgrossde** [comment]
I have no time to continue nw-notifys development at the moment. Please use the [new rich notification system](http://nwjs.io/blog/whats-new-in-0.13/#chrome-api-support) (nw 0.13+) or submit a PR if you can find the cause of this bug.
