### ISSUE TITLE
Application disappear from dock on mac

### ISSUE THREAD

**Issue by Paxa** [cgrossde/nw-notify#3]
I call `nw-notify` to open notification then application disappear from dock, also can not see with <key>cmd</key>+<key>tab</key>.

How to fix it?

**Comment by Paxa** [comment]
Problem is in `show_in_taskbar`, on windows it should be false, but on mac - true

**Comment by Paxa** [comment]
I think it would be nice to be able extend new window params

**Comment by cgrossde** [comment]
Can you supply some sample code so I can test this real quick?

**Comment by Paxa** [comment]
```js
var showHtmlNotification = function (icon, title, body) {
  var notifier = require('nw-notify');

  // give it nice look
  notifier.setConfig({
    defaultStyleContainer: {
      border: '1px solid #9D9D9D',
      borderRadius: '6px',
      backgroundColor: 'rgba(245, 245, 245, 0.94)',
      fontFamily: 'Helvetica Neue',
      boxShadow: '0px 0px 11px rgba(0, 0, 0, 0.4)',
      fontSize: 12,
      position: 'relative',
      lineHeight: '17px',
      padding: '8px 12px 8px 14px'
    }
  });

  if (icon) icon = notifier.getAppPath() + icon;
  notifier.notify(title, body, false, icon, callback);
};

showHtmlNotification(undefined, "Taxi is arrived", 'hurry up');
```

I temporary solved by:
```js
'show_in_taskbar': false, // replace with
'show_in_taskbar': process.platform == "darwin",
```

Also would like to have:

* access to notification object `var notif = notifier.notify(...)'
* callback on click, just callback instead of `gui.Shell.openExternal`
* callback on show
* callback on close

**Comment by Paxa** [comment]
Here is example application https://github.com/Paxa/nw-sample-apps/tree/notifications-app/notifications

**Comment by cgrossde** [comment]
@Paxa thanks for your input :+1:  I fixed the initial bug and did some changes:

* added onClick, onShow, onClose handlers
* fixed missing border-radius
* allow to pass an object to notify

Example: 

~~~
notify({
    title: 'Title',
    text: 'Some text',
    url: 'http://google.de',
    onClickFunc: function() { alert('onCLick') },
    onShowFunc: function() { alert('onShow') },
    onCloseFunc: function() { alert('onClose')}
});
~~~

You can find those changes in the **issue-3** branch. Please check them out and give me feedback.

Why do you need access to the notification object? This would be a little bit cumbersome to implement. And could lead to side effects.

**Comment by Paxa** [comment]
Awesome. Tested, working in my sample app.

I need notification object to manually close notification. For example close on click or close on timeout. Anyway it's not critical.

And If it's possible:
```js
var closeNotification = function(event) {
  if (notificationObj.onCloseFunc) {
    notificationObj.onCloseFunc(event);
  }

// and 

closeButton.addEventListener('click', function(event) {
  event.stopPropagation();
  animationQueue.push({
    'func': closeNotification,
     'args': [event]
  });
});
```

So we can detect if notification closed by timeout or by user

**Comment by cgrossde** [comment]
I think returning some kind of event with the onClick, onShow, onClose callbacks is a good idea. Maybe something like this:

~~~
{
  name: 'show/click/timeout/close',
  id: 88,
  notificationObj: {}
}
~~~

And then add a new method to `nw-notify`:
**notifier.close(id)**

I reuse the windows for multiple notifications so I can't just give you the `closeNotification` function, but I could give you the ID and will then manage internally if the notification with that ID was already closed or not.

**Comment by Paxa** [comment]
Sounds good

**Comment by cgrossde** [comment]
@Paxa Please test again if the new release works for you. The `onShowFunc` and `onClickFunc` callbacks now return an event which also has a `closeNotification` function attached :wink:

**Comment by Paxa** [comment]
Working well, thanks!
