### ISSUE TITLE
Cannot call method 'Init' of undefined 

### ISSUE THREAD

**Issue by alexcroox** [cgrossde/nw-notify#4]
When I run my app on Windows without packing any of the source this module works great. However when I use [nodebob](https://github.com/geo8bit/nodebob) which packages my app for me it immediately errors out on load with the following:

```Uncaught TypeError: Cannot call method 'Init' of undefined C:\Users\IEUser\AppData\Local\Temp\nw3704_29724\node_modules\nw-notify\index.js:131```

which is this line:

`gui.Screen.Init();`

Any idea what might cause this?

**Comment by cgrossde** [comment]
It seems the node-webkit var `gui` is not available to the node modules. I have no idea why, please open an issue at nodebob or use [node-webkit-builder](https://github.com/mllrsohn/node-webkit-builder)

**Comment by cgrossde** [comment]
I took a look at this again, my initial assumption was wrong.

The cause is this code:
```Javascript
var gui = global.window.nwDispatcher.requireNwGui();
// Init screen to gather some information
gui.Screen.Init();
```
And seems to be related to nwjs/nw.js#2465. Please try to instruct `nodebob` to use a newer version of `node-webkit` and try again.

**Comment by alexcroox** [comment]
Thank you for looking into this! I'll update the files in here manually and let nodebob know if that fixes it :)

https://github.com/geo8bit/nodebob/tree/master/buildTools/nw
