### ISSUE TITLE
"npm start" makes a lot of empty folders

### ISSUE THREAD

**Issue by fateyan** [cgrossde/nw-notify#6]
My package.json :
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "", 
  "main": "index.html",
  "author": "", 
  "scripts": {
    "start": "nw --enable-transparent-visuals --disable-gpu" 
  },  
  "dependencies": {
    "nw-notify": "^0.1.1"
  },  
  "window": {
    "transparent": true,
    "frame": false,
    "toolbar": false
  }
}
```
npm version 2.9.0

I only use `notify()` in my code.

`npm start` makes some empty folders, like `.org.chromium.Chromium.***** (asterisk is hash)`

This happens when I use `npm start`, but `nw --enable-transparent-visuals --disable-gpu`  works correctly.

**Comment by cgrossde** [comment]
Seems more like an npm problem? Can you test this with version 0.2.0 of nw-notify?

**Comment by fateyan** [comment]
I got the same result from version 0.2.0.

The main process of npm didn't terminated after I closed my application window, I have to close it by Ctrl-C.
Is it a problem of nw-notify?

**Comment by cgrossde** [comment]
It shouldn't, did you call `nwNotify.closeAll`?

**Comment by fateyan** [comment]
Thanks for your reply.

I used `notify.closeAll()`, but it didn't help me.

I solved this problem by 
```javascript
var gui = require('nw.gui');
var win = gui.Window.get();

win.on('close', function() {
    process.quit();
});
```

**Comment by cgrossde** [comment]
Can you please provide me with your index.html. You shouldn't need to execute process quit

**Comment by fateyan** [comment]
This is my index.html
https://gist.github.com/fateyan/4805012360c1a030866c

Thanks !

**Comment by Paxa** [comment]
Had same problem here  https://github.com/zcbenz/nw-sample-apps/tree/master/notifications

When one of notifications is open - it start to act as multi-window application, so when close main window application don't exit.

Solved by:
```js
// for nw-notify frameless windows
NW.Window.get().on('close', function() {
  NW.App.quit();
});
```

**Comment by cgrossde** [comment]
I'm still not sure if node-webkit is supposed to exit after executing the javascript. It's a browser after all and this seems to me like normal behavior. I will file this as a bug if your test case exits when you remove all nw-notify related code. Could you please give me feedback on this?

**Comment by cgrossde** [comment]
Will close this for now, reopen if you think this is a bug.
